// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAba3XU6QhEs7YsNW8A_F1wnqw8_5L9ulo',
    appId: '1:512920839675:web:398f61073d7b8c8368575e',
    messagingSenderId: '512920839675',
    projectId: 'pomodoro-timer-a38cc',
    authDomain: 'pomodoro-timer-a38cc.firebaseapp.com',
    storageBucket: 'pomodoro-timer-a38cc.firebasestorage.app',
    measurementId: 'G-7T2T3PXPNS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXtkQD-7f5JV07oTes-DgfEKuz4KcEPS8',
    appId: '1:512920839675:android:c51596f5b58d212c68575e',
    messagingSenderId: '512920839675',
    projectId: 'pomodoro-timer-a38cc',
    storageBucket: 'pomodoro-timer-a38cc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6qOiCtd9APOqRo7xxozyjq2zOz6FE174',
    appId: '1:512920839675:ios:b7eeaa4c885a8fd368575e',
    messagingSenderId: '512920839675',
    projectId: 'pomodoro-timer-a38cc',
    storageBucket: 'pomodoro-timer-a38cc.firebasestorage.app',
    iosBundleId: 'com.example.pomadoro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6qOiCtd9APOqRo7xxozyjq2zOz6FE174',
    appId: '1:512920839675:ios:b7eeaa4c885a8fd368575e',
    messagingSenderId: '512920839675',
    projectId: 'pomodoro-timer-a38cc',
    storageBucket: 'pomodoro-timer-a38cc.firebasestorage.app',
    iosBundleId: 'com.example.pomadoro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAba3XU6QhEs7YsNW8A_F1wnqw8_5L9ulo',
    appId: '1:512920839675:web:0ad19a619f38e45768575e',
    messagingSenderId: '512920839675',
    projectId: 'pomodoro-timer-a38cc',
    authDomain: 'pomodoro-timer-a38cc.firebaseapp.com',
    storageBucket: 'pomodoro-timer-a38cc.firebasestorage.app',
    measurementId: 'G-P73R5L4DRW',
  );

}